// Master countries configuration for the Voice Translator application
// This file contains the complete list of all countries in the world

const countries = {
  // North America
  'US': { name: 'United States', isActive: true },
  'CA': { name: 'Canada', isActive: true },
  'MX': { name: 'Mexico', isActive: true },
  'GT': { name: 'Guatemala', isActive: true },
  'BZ': { name: 'Belize', isActive: true },
  'SV': { name: 'El Salvador', isActive: true },
  'HN': { name: 'Honduras', isActive: true },
  'NI': { name: 'Nicaragua', isActive: true },
  'CR': { name: 'Costa Rica', isActive: true },
  'PA': { name: 'Panama', isActive: true },
  'CU': { name: 'Cuba', isActive: true },
  'JM': { name: 'Jamaica', isActive: true },
  'HT': { name: 'Haiti', isActive: true },
  'DO': { name: 'Dominican Republic', isActive: true },
  'PR': { name: 'Puerto Rico', isActive: true },
  'TT': { name: 'Trinidad and Tobago', isActive: true },
  'BB': { name: 'Barbados', isActive: true },
  'GD': { name: 'Grenada', isActive: true },
  'LC': { name: 'Saint Lucia', isActive: true },
  'VC': { name: 'Saint Vincent and the Grenadines', isActive: true },
  'AG': { name: 'Antigua and Barbuda', isActive: true },
  'KN': { name: 'Saint Kitts and Nevis', isActive: true },
  'DM': { name: 'Dominica', isActive: true },
  'BS': { name: 'Bahamas', isActive: true },

  // Europe
  'GB': { name: 'United Kingdom', isActive: true },
  'DE': { name: 'Germany', isActive: true },
  'FR': { name: 'France', isActive: true },
  'IT': { name: 'Italy', isActive: true },
  'ES': { name: 'Spain', isActive: true },
  'NL': { name: 'Netherlands', isActive: true },
  'PL': { name: 'Poland', isActive: true },
  'RU': { name: 'Russia', isActive: true },
  'CH': { name: 'Switzerland', isActive: true },
  'SE': { name: 'Sweden', isActive: true },
  'NO': { name: 'Norway', isActive: true },
  'DK': { name: 'Denmark', isActive: true },
  'FI': { name: 'Finland', isActive: true },
  'BE': { name: 'Belgium', isActive: true },
  'AT': { name: 'Austria', isActive: true },
  'IE': { name: 'Ireland', isActive: true },
  'PT': { name: 'Portugal', isActive: true },
  'GR': { name: 'Greece', isActive: true },
  'CZ': { name: 'Czech Republic', isActive: true },
  'SK': { name: 'Slovakia', isActive: true },
  'HU': { name: 'Hungary', isActive: true },
  'RO': { name: 'Romania', isActive: true },
  'BG': { name: 'Bulgaria', isActive: true },
  'HR': { name: 'Croatia', isActive: true },
  'SI': { name: 'Slovenia', isActive: true },
  'EE': { name: 'Estonia', isActive: true },
  'LV': { name: 'Latvia', isActive: true },
  'LT': { name: 'Lithuania', isActive: true },
  'MT': { name: 'Malta', isActive: true },
  'CY': { name: 'Cyprus', isActive: true },
  'LU': { name: 'Luxembourg', isActive: true },
  'IS': { name: 'Iceland', isActive: true },
  'AL': { name: 'Albania', isActive: true },
  'MK': { name: 'North Macedonia', isActive: true },
  'ME': { name: 'Montenegro', isActive: true },
  'RS': { name: 'Serbia', isActive: true },
  'BA': { name: 'Bosnia and Herzegovina', isActive: true },
  'XK': { name: 'Kosovo', isActive: true },
  'MD': { name: 'Moldova', isActive: true },
  'UA': { name: 'Ukraine', isActive: true },
  'BY': { name: 'Belarus', isActive: true },
  'AM': { name: 'Armenia', isActive: true },
  'GE': { name: 'Georgia', isActive: true },
  'AZ': { name: 'Azerbaijan', isActive: true },
  'KZ': { name: 'Kazakhstan', isActive: true },
  'UZ': { name: 'Uzbekistan', isActive: true },
  'TM': { name: 'Turkmenistan', isActive: true },
  'KG': { name: 'Kyrgyzstan', isActive: true },
  'TJ': { name: 'Tajikistan', isActive: true },

  // Asia
  'CN': { name: 'China', isActive: true },
  'IN': { name: 'India', isActive: true },
  'JP': { name: 'Japan', isActive: true },
  'KR': { name: 'South Korea', isActive: true },
  'SG': { name: 'Singapore', isActive: true },
  'MY': { name: 'Malaysia', isActive: true },
  'TH': { name: 'Thailand', isActive: true },
  'VN': { name: 'Vietnam', isActive: true },
  'ID': { name: 'Indonesia', isActive: true },
  'PH': { name: 'Philippines', isActive: true },
  'PK': { name: 'Pakistan', isActive: true },
  'BD': { name: 'Bangladesh', isActive: true },
  'LK': { name: 'Sri Lanka', isActive: true },
  'NP': { name: 'Nepal', isActive: true },
  'BT': { name: 'Bhutan', isActive: true },
  'MV': { name: 'Maldives', isActive: true },
  'MM': { name: 'Myanmar', isActive: true },
  'LA': { name: 'Laos', isActive: true },
  'KH': { name: 'Cambodia', isActive: true },
  'MN': { name: 'Mongolia', isActive: true },
  'TW': { name: 'Taiwan', isActive: true },
  'HK': { name: 'Hong Kong', isActive: true },
  'MO': { name: 'Macau', isActive: true },
  'BN': { name: 'Brunei', isActive: true },
  'TL': { name: 'Timor-Leste', isActive: true },
  'PG': { name: 'Papua New Guinea', isActive: true },
  'FJ': { name: 'Fiji', isActive: true },
  'NC': { name: 'New Caledonia', isActive: true },
  'VU': { name: 'Vanuatu', isActive: true },
  'SB': { name: 'Solomon Islands', isActive: true },
  'TO': { name: 'Tonga', isActive: true },
  'WS': { name: 'Samoa', isActive: true },
  'KI': { name: 'Kiribati', isActive: true },
  'TV': { name: 'Tuvalu', isActive: true },
  'NR': { name: 'Nauru', isActive: true },
  'PW': { name: 'Palau', isActive: true },
  'MH': { name: 'Marshall Islands', isActive: true },
  'FM': { name: 'Micronesia', isActive: true },
  'CK': { name: 'Cook Islands', isActive: true },
  'NU': { name: 'Niue', isActive: true },
  'TK': { name: 'Tokelau', isActive: true },
  'AS': { name: 'American Samoa', isActive: true },
  'GU': { name: 'Guam', isActive: true },
  'MP': { name: 'Northern Mariana Islands', isActive: true },
  'PF': { name: 'French Polynesia', isActive: true },
  'WF': { name: 'Wallis and Futuna', isActive: true },

  // Middle East
  'SA': { name: 'Saudi Arabia', isActive: true },
  'AE': { name: 'United Arab Emirates', isActive: true },
  'TR': { name: 'Turkey', isActive: true },
  'IL': { name: 'Israel', isActive: true },
  'JO': { name: 'Jordan', isActive: true },
  'LB': { name: 'Lebanon', isActive: true },
  'SY': { name: 'Syria', isActive: true },
  'IQ': { name: 'Iraq', isActive: true },
  'IR': { name: 'Iran', isActive: true },
  'KW': { name: 'Kuwait', isActive: true },
  'QA': { name: 'Qatar', isActive: true },
  'BH': { name: 'Bahrain', isActive: true },
  'OM': { name: 'Oman', isActive: true },
  'YE': { name: 'Yemen', isActive: true },
  'PS': { name: 'Palestine', isActive: true },

  // Africa
  'NG': { name: 'Nigeria', isActive: true },
  'ZA': { name: 'South Africa', isActive: true },
  'EG': { name: 'Egypt', isActive: true },
  'KE': { name: 'Kenya', isActive: true },
  'GH': { name: 'Ghana', isActive: true },
  'ET': { name: 'Ethiopia', isActive: true },
  'TZ': { name: 'Tanzania', isActive: true },
  'UG': { name: 'Uganda', isActive: true },
  'MG': { name: 'Madagascar', isActive: true },
  'MZ': { name: 'Mozambique', isActive: true },
  'ZW': { name: 'Zimbabwe', isActive: true },
  'ZM': { name: 'Zambia', isActive: true },
  'MW': { name: 'Malawi', isActive: true },
  'BW': { name: 'Botswana', isActive: true },
  'NA': { name: 'Namibia', isActive: true },
  'SZ': { name: 'Eswatini', isActive: true },
  'LS': { name: 'Lesotho', isActive: true },
  'AO': { name: 'Angola', isActive: true },
  'CD': { name: 'Democratic Republic of the Congo', isActive: true },
  'CG': { name: 'Republic of the Congo', isActive: true },
  'GA': { name: 'Gabon', isActive: true },
  'CM': { name: 'Cameroon', isActive: true },
  'CF': { name: 'Central African Republic', isActive: true },
  'TD': { name: 'Chad', isActive: true },
  'NE': { name: 'Niger', isActive: true },
  'ML': { name: 'Mali', isActive: true },
  'BF': { name: 'Burkina Faso', isActive: true },
  'CI': { name: 'Ivory Coast', isActive: true },
  'SN': { name: 'Senegal', isActive: true },
  'GN': { name: 'Guinea', isActive: true },
  'GW': { name: 'Guinea-Bissau', isActive: true },
  'SL': { name: 'Sierra Leone', isActive: true },
  'LR': { name: 'Liberia', isActive: true },
  'TG': { name: 'Togo', isActive: true },
  'BJ': { name: 'Benin', isActive: true },
  'CV': { name: 'Cape Verde', isActive: true },
  'GM': { name: 'Gambia', isActive: true },
  'MR': { name: 'Mauritania', isActive: true },
  'DZ': { name: 'Algeria', isActive: true },
  'TN': { name: 'Tunisia', isActive: true },
  'LY': { name: 'Libya', isActive: true },
  'SD': { name: 'Sudan', isActive: true },
  'SS': { name: 'South Sudan', isActive: true },
  'ER': { name: 'Eritrea', isActive: true },
  'DJ': { name: 'Djibouti', isActive: true },
  'SO': { name: 'Somalia', isActive: true },
  'RW': { name: 'Rwanda', isActive: true },
  'BI': { name: 'Burundi', isActive: true },
  'KM': { name: 'Comoros', isActive: true },
  'SC': { name: 'Seychelles', isActive: true },
  'MU': { name: 'Mauritius', isActive: true },
  'RE': { name: 'Réunion', isActive: true },
  'YT': { name: 'Mayotte', isActive: true },
  'ST': { name: 'São Tomé and Príncipe', isActive: true },
  'GQ': { name: 'Equatorial Guinea', isActive: true },
  'SH': { name: 'Saint Helena', isActive: true },
  'AC': { name: 'Ascension Island', isActive: true },
  'TA': { name: 'Tristan da Cunha', isActive: true },

  // South America
  'BR': { name: 'Brazil', isActive: true },
  'AR': { name: 'Argentina', isActive: true },
  'CO': { name: 'Colombia', isActive: true },
  'PE': { name: 'Peru', isActive: true },
  'CL': { name: 'Chile', isActive: true },
  'VE': { name: 'Venezuela', isActive: true },
  'EC': { name: 'Ecuador', isActive: true },
  'BO': { name: 'Bolivia', isActive: true },
  'PY': { name: 'Paraguay', isActive: true },
  'UY': { name: 'Uruguay', isActive: true },
  'GY': { name: 'Guyana', isActive: true },
  'SR': { name: 'Suriname', isActive: true },
  'FK': { name: 'Falkland Islands', isActive: true },
  'GF': { name: 'French Guiana', isActive: true },

  // Australia & Oceania
  'AU': { name: 'Australia', isActive: true },
  'NZ': { name: 'New Zealand', isActive: true }
};

module.exports = { countries };
