// Master country codes configuration for the Voice Translator application
// This file contains the complete list of all country codes in the world

const countryCodes = {
  // North America
  'US': { country: 'United States', countryCode: 'US', isActive: true },
  'CA': { country: 'Canada', countryCode: 'CA', isActive: true },
  'MX': { country: 'Mexico', countryCode: 'MX', isActive: true },
  'GT': { country: 'Guatemala', countryCode: 'GT', isActive: true },
  'BZ': { country: 'Belize', countryCode: 'BZ', isActive: true },
  'SV': { country: 'El Salvador', countryCode: 'SV', isActive: true },
  'HN': { country: 'Honduras', countryCode: 'HN', isActive: true },
  'NI': { country: 'Nicaragua', countryCode: 'NI', isActive: true },
  'CR': { country: 'Costa Rica', countryCode: 'CR', isActive: true },
  'PA': { country: 'Panama', countryCode: 'PA', isActive: true },
  'CU': { country: 'Cuba', countryCode: 'CU', isActive: true },
  'JM': { country: 'Jamaica', countryCode: 'JM', isActive: true },
  'HT': { country: 'Haiti', countryCode: 'HT', isActive: true },
  'DO': { country: 'Dominican Republic', countryCode: 'DO', isActive: true },
  'PR': { country: 'Puerto Rico', countryCode: 'PR', isActive: true },
  'TT': { country: 'Trinidad and Tobago', countryCode: 'TT', isActive: true },
  'BB': { country: 'Barbados', countryCode: 'BB', isActive: true },
  'GD': { country: 'Grenada', countryCode: 'GD', isActive: true },
  'LC': { country: 'Saint Lucia', countryCode: 'LC', isActive: true },
  'VC': { country: 'Saint Vincent and the Grenadines', countryCode: 'VC', isActive: true },
  'AG': { country: 'Antigua and Barbuda', countryCode: 'AG', isActive: true },
  'KN': { country: 'Saint Kitts and Nevis', countryCode: 'KN', isActive: true },
  'DM': { country: 'Dominica', countryCode: 'DM', isActive: true },
  'BS': { country: 'Bahamas', countryCode: 'BS', isActive: true },

  // Europe
  'GB': { country: 'United Kingdom', countryCode: 'GB', isActive: true },
  'DE': { country: 'Germany', countryCode: 'DE', isActive: true },
  'FR': { country: 'France', countryCode: 'FR', isActive: true },
  'IT': { country: 'Italy', countryCode: 'IT', isActive: true },
  'ES': { country: 'Spain', countryCode: 'ES', isActive: true },
  'NL': { country: 'Netherlands', countryCode: 'NL', isActive: true },
  'PL': { country: 'Poland', countryCode: 'PL', isActive: true },
  'RU': { country: 'Russia', countryCode: 'RU', isActive: true },
  'CH': { country: 'Switzerland', countryCode: 'CH', isActive: true },
  'SE': { country: 'Sweden', countryCode: 'SE', isActive: true },
  'NO': { country: 'Norway', countryCode: 'NO', isActive: true },
  'DK': { country: 'Denmark', countryCode: 'DK', isActive: true },
  'FI': { country: 'Finland', countryCode: 'FI', isActive: true },
  'BE': { country: 'Belgium', countryCode: 'BE', isActive: true },
  'AT': { country: 'Austria', countryCode: 'AT', isActive: true },
  'IE': { country: 'Ireland', countryCode: 'IE', isActive: true },
  'PT': { country: 'Portugal', countryCode: 'PT', isActive: true },
  'GR': { country: 'Greece', countryCode: 'GR', isActive: true },
  'CZ': { country: 'Czech Republic', countryCode: 'CZ', isActive: true },
  'SK': { country: 'Slovakia', countryCode: 'SK', isActive: true },
  'HU': { country: 'Hungary', countryCode: 'HU', isActive: true },
  'RO': { country: 'Romania', countryCode: 'RO', isActive: true },
  'BG': { country: 'Bulgaria', countryCode: 'BG', isActive: true },
  'HR': { country: 'Croatia', countryCode: 'HR', isActive: true },
  'SI': { country: 'Slovenia', countryCode: 'SI', isActive: true },
  'EE': { country: 'Estonia', countryCode: 'EE', isActive: true },
  'LV': { country: 'Latvia', countryCode: 'LV', isActive: true },
  'LT': { country: 'Lithuania', countryCode: 'LT', isActive: true },
  'MT': { country: 'Malta', countryCode: 'MT', isActive: true },
  'CY': { country: 'Cyprus', countryCode: 'CY', isActive: true },
  'LU': { country: 'Luxembourg', countryCode: 'LU', isActive: true },
  'IS': { country: 'Iceland', countryCode: 'IS', isActive: true },
  'AL': { country: 'Albania', countryCode: 'AL', isActive: true },
  'MK': { country: 'North Macedonia', countryCode: 'MK', isActive: true },
  'ME': { country: 'Montenegro', countryCode: 'ME', isActive: true },
  'RS': { country: 'Serbia', countryCode: 'RS', isActive: true },
  'BA': { country: 'Bosnia and Herzegovina', countryCode: 'BA', isActive: true },
  'XK': { country: 'Kosovo', countryCode: 'XK', isActive: true },
  'MD': { country: 'Moldova', countryCode: 'MD', isActive: true },
  'UA': { country: 'Ukraine', countryCode: 'UA', isActive: true },
  'BY': { country: 'Belarus', countryCode: 'BY', isActive: true },
  'AM': { country: 'Armenia', countryCode: 'AM', isActive: true },
  'GE': { country: 'Georgia', countryCode: 'GE', isActive: true },
  'AZ': { country: 'Azerbaijan', countryCode: 'AZ', isActive: true },
  'KZ': { country: 'Kazakhstan', countryCode: 'KZ', isActive: true },
  'UZ': { country: 'Uzbekistan', countryCode: 'UZ', isActive: true },
  'TM': { country: 'Turkmenistan', countryCode: 'TM', isActive: true },
  'KG': { country: 'Kyrgyzstan', countryCode: 'KG', isActive: true },
  'TJ': { country: 'Tajikistan', countryCode: 'TJ', isActive: true },

  // Asia
  'CN': { country: 'China', countryCode: 'CN', isActive: true },
  'IN': { country: 'India', countryCode: 'IN', isActive: true },
  'JP': { country: 'Japan', countryCode: 'JP', isActive: true },
  'KR': { country: 'South Korea', countryCode: 'KR', isActive: true },
  'SG': { country: 'Singapore', countryCode: 'SG', isActive: true },
  'MY': { country: 'Malaysia', countryCode: 'MY', isActive: true },
  'TH': { country: 'Thailand', countryCode: 'TH', isActive: true },
  'VN': { country: 'Vietnam', countryCode: 'VN', isActive: true },
  'ID': { country: 'Indonesia', countryCode: 'ID', isActive: true },
  'PH': { country: 'Philippines', countryCode: 'PH', isActive: true },
  'PK': { country: 'Pakistan', countryCode: 'PK', isActive: true },
  'BD': { country: 'Bangladesh', countryCode: 'BD', isActive: true },
  'LK': { country: 'Sri Lanka', countryCode: 'LK', isActive: true },
  'NP': { country: 'Nepal', countryCode: 'NP', isActive: true },
  'BT': { country: 'Bhutan', countryCode: 'BT', isActive: true },
  'MV': { country: 'Maldives', countryCode: 'MV', isActive: true },
  'MM': { country: 'Myanmar', countryCode: 'MM', isActive: true },
  'LA': { country: 'Laos', countryCode: 'LA', isActive: true },
  'KH': { country: 'Cambodia', countryCode: 'KH', isActive: true },
  'MN': { country: 'Mongolia', countryCode: 'MN', isActive: true },
  'TW': { country: 'Taiwan', countryCode: 'TW', isActive: true },
  'HK': { country: 'Hong Kong', countryCode: 'HK', isActive: true },
  'MO': { country: 'Macau', countryCode: 'MO', isActive: true },
  'BN': { country: 'Brunei', countryCode: 'BN', isActive: true },
  'TL': { country: 'Timor-Leste', countryCode: 'TL', isActive: true },
  'PG': { country: 'Papua New Guinea', countryCode: 'PG', isActive: true },
  'FJ': { country: 'Fiji', countryCode: 'FJ', isActive: true },
  'NC': { country: 'New Caledonia', countryCode: 'NC', isActive: true },
  'VU': { country: 'Vanuatu', countryCode: 'VU', isActive: true },
  'SB': { country: 'Solomon Islands', countryCode: 'SB', isActive: true },
  'TO': { country: 'Tonga', countryCode: 'TO', isActive: true },
  'WS': { country: 'Samoa', countryCode: 'WS', isActive: true },
  'KI': { country: 'Kiribati', countryCode: 'KI', isActive: true },
  'TV': { country: 'Tuvalu', countryCode: 'TV', isActive: true },
  'NR': { country: 'Nauru', countryCode: 'NR', isActive: true },
  'PW': { country: 'Palau', countryCode: 'PW', isActive: true },
  'MH': { country: 'Marshall Islands', countryCode: 'MH', isActive: true },
  'FM': { country: 'Micronesia', countryCode: 'FM', isActive: true },
  'CK': { country: 'Cook Islands', countryCode: 'CK', isActive: true },
  'NU': { country: 'Niue', countryCode: 'NU', isActive: true },
  'TK': { country: 'Tokelau', countryCode: 'TK', isActive: true },
  'AS': { country: 'American Samoa', countryCode: 'AS', isActive: true },
  'GU': { country: 'Guam', countryCode: 'GU', isActive: true },
  'MP': { country: 'Northern Mariana Islands', countryCode: 'MP', isActive: true },
  'PF': { country: 'French Polynesia', countryCode: 'PF', isActive: true },
  'WF': { country: 'Wallis and Futuna', countryCode: 'WF', isActive: true },

  // Middle East
  'SA': { country: 'Saudi Arabia', countryCode: 'SA', isActive: true },
  'AE': { country: 'United Arab Emirates', countryCode: 'AE', isActive: true },
  'TR': { country: 'Turkey', countryCode: 'TR', isActive: true },
  'IL': { country: 'Israel', countryCode: 'IL', isActive: true },
  'JO': { country: 'Jordan', countryCode: 'JO', isActive: true },
  'LB': { country: 'Lebanon', countryCode: 'LB', isActive: true },
  'SY': { country: 'Syria', countryCode: 'SY', isActive: true },
  'IQ': { country: 'Iraq', countryCode: 'IQ', isActive: true },
  'IR': { country: 'Iran', countryCode: 'IR', isActive: true },
  'KW': { country: 'Kuwait', countryCode: 'KW', isActive: true },
  'QA': { country: 'Qatar', countryCode: 'QA', isActive: true },
  'BH': { country: 'Bahrain', countryCode: 'BH', isActive: true },
  'OM': { country: 'Oman', countryCode: 'OM', isActive: true },
  'YE': { country: 'Yemen', countryCode: 'YE', isActive: true },
  'PS': { country: 'Palestine', countryCode: 'PS', isActive: true },

  // Africa
  'NG': { country: 'Nigeria', countryCode: 'NG', isActive: true },
  'ZA': { country: 'South Africa', countryCode: 'ZA', isActive: true },
  'EG': { country: 'Egypt', countryCode: 'EG', isActive: true },
  'KE': { country: 'Kenya', countryCode: 'KE', isActive: true },
  'GH': { country: 'Ghana', countryCode: 'GH', isActive: true },
  'ET': { country: 'Ethiopia', countryCode: 'ET', isActive: true },
  'TZ': { country: 'Tanzania', countryCode: 'TZ', isActive: true },
  'UG': { country: 'Uganda', countryCode: 'UG', isActive: true },
  'MG': { country: 'Madagascar', countryCode: 'MG', isActive: true },
  'MZ': { country: 'Mozambique', countryCode: 'MZ', isActive: true },
  'ZW': { country: 'Zimbabwe', countryCode: 'ZW', isActive: true },
  'ZM': { country: 'Zambia', countryCode: 'ZM', isActive: true },
  'MW': { country: 'Malawi', countryCode: 'MW', isActive: true },
  'BW': { country: 'Botswana', countryCode: 'BW', isActive: true },
  'NA': { country: 'Namibia', countryCode: 'NA', isActive: true },
  'SZ': { country: 'Eswatini', countryCode: 'SZ', isActive: true },
  'LS': { country: 'Lesotho', countryCode: 'LS', isActive: true },
  'AO': { country: 'Angola', countryCode: 'AO', isActive: true },
  'CD': { country: 'Democratic Republic of the Congo', countryCode: 'CD', isActive: true },
  'CG': { country: 'Republic of the Congo', countryCode: 'CG', isActive: true },
  'GA': { country: 'Gabon', countryCode: 'GA', isActive: true },
  'CM': { country: 'Cameroon', countryCode: 'CM', isActive: true },
  'CF': { country: 'Central African Republic', countryCode: 'CF', isActive: true },
  'TD': { country: 'Chad', countryCode: 'TD', isActive: true },
  'NE': { country: 'Niger', countryCode: 'NE', isActive: true },
  'ML': { country: 'Mali', countryCode: 'ML', isActive: true },
  'BF': { country: 'Burkina Faso', countryCode: 'BF', isActive: true },
  'CI': { country: 'Ivory Coast', countryCode: 'CI', isActive: true },
  'SN': { country: 'Senegal', countryCode: 'SN', isActive: true },
  'GN': { country: 'Guinea', countryCode: 'GN', isActive: true },
  'GW': { country: 'Guinea-Bissau', countryCode: 'GW', isActive: true },
  'SL': { country: 'Sierra Leone', countryCode: 'SL', isActive: true },
  'LR': { country: 'Liberia', countryCode: 'LR', isActive: true },
  'TG': { country: 'Togo', countryCode: 'TG', isActive: true },
  'BJ': { country: 'Benin', countryCode: 'BJ', isActive: true },
  'CV': { country: 'Cape Verde', countryCode: 'CV', isActive: true },
  'GM': { country: 'Gambia', countryCode: 'GM', isActive: true },
  'MR': { country: 'Mauritania', countryCode: 'MR', isActive: true },
  'DZ': { country: 'Algeria', countryCode: 'DZ', isActive: true },
  'TN': { country: 'Tunisia', countryCode: 'TN', isActive: true },
  'LY': { country: 'Libya', countryCode: 'LY', isActive: true },
  'SD': { country: 'Sudan', countryCode: 'SD', isActive: true },
  'SS': { country: 'South Sudan', countryCode: 'SS', isActive: true },
  'ER': { country: 'Eritrea', countryCode: 'ER', isActive: true },
  'DJ': { country: 'Djibouti', countryCode: 'DJ', isActive: true },
  'SO': { country: 'Somalia', countryCode: 'SO', isActive: true },
  'RW': { country: 'Rwanda', countryCode: 'RW', isActive: true },
  'BI': { country: 'Burundi', countryCode: 'BI', isActive: true },
  'KM': { country: 'Comoros', countryCode: 'KM', isActive: true },
  'SC': { country: 'Seychelles', countryCode: 'SC', isActive: true },
  'MU': { country: 'Mauritius', countryCode: 'MU', isActive: true },
  'RE': { country: 'Réunion', countryCode: 'RE', isActive: true },
  'YT': { country: 'Mayotte', countryCode: 'YT', isActive: true },
  'ST': { country: 'São Tomé and Príncipe', countryCode: 'ST', isActive: true },
  'GQ': { country: 'Equatorial Guinea', countryCode: 'GQ', isActive: true },
  'SH': { country: 'Saint Helena', countryCode: 'SH', isActive: true },
  'AC': { country: 'Ascension Island', countryCode: 'AC', isActive: true },
  'TA': { country: 'Tristan da Cunha', countryCode: 'TA', isActive: true },

  // South America
  'BR': { country: 'Brazil', countryCode: 'BR', isActive: true },
  'AR': { country: 'Argentina', countryCode: 'AR', isActive: true },
  'CO': { country: 'Colombia', countryCode: 'CO', isActive: true },
  'PE': { country: 'Peru', countryCode: 'PE', isActive: true },
  'CL': { country: 'Chile', countryCode: 'CL', isActive: true },
  'VE': { country: 'Venezuela', countryCode: 'VE', isActive: true },
  'EC': { country: 'Ecuador', countryCode: 'EC', isActive: true },
  'BO': { country: 'Bolivia', countryCode: 'BO', isActive: true },
  'PY': { country: 'Paraguay', countryCode: 'PY', isActive: true },
  'UY': { country: 'Uruguay', countryCode: 'UY', isActive: true },
  'GY': { country: 'Guyana', countryCode: 'GY', isActive: true },
  'SR': { country: 'Suriname', countryCode: 'SR', isActive: true },
  'FK': { country: 'Falkland Islands', countryCode: 'FK', isActive: true },
  'GF': { country: 'French Guiana', countryCode: 'GF', isActive: true },

  // Australia & Oceania
  'AU': { country: 'Australia', countryCode: 'AU', isActive: true },
  'NZ': { country: 'New Zealand', countryCode: 'NZ', isActive: true }
};

module.exports = { countryCodes };
