// Master country codes configuration for the Voice Translator application
// This file contains international dialing codes for phone numbers

const countryCodes = {
  // North America
  'US': { country: 'United States', countryCode: 'US', dialingCode: '+1', isActive: true },
  'CA': { country: 'Canada', countryCode: 'CA', dialingCode: '+1', isActive: true },
  'MX': { country: 'Mexico', countryCode: 'MX', dialingCode: '+52', isActive: true },
  'GT': { country: 'Guatemala', countryCode: 'GT', dialingCode: '+502', isActive: true },
  'BZ': { country: 'Belize', countryCode: 'BZ', dialingCode: '+501', isActive: true },
  'SV': { country: 'El Salvador', countryCode: 'SV', dialingCode: '+503', isActive: true },
  'HN': { country: 'Honduras', countryCode: 'HN', dialingCode: '+504', isActive: true },
  'NI': { country: 'Nicaragua', countryCode: 'NI', dialingCode: '+505', isActive: true },
  'CR': { country: 'Costa Rica', countryCode: 'CR', dialingCode: '+506', isActive: true },
  'PA': { country: 'Panama', countryCode: 'PA', dialingCode: '+507', isActive: true },
  'CU': { country: 'Cuba', countryCode: 'CU', dialingCode: '+53', isActive: true },
  'JM': { country: 'Jamaica', countryCode: 'JM', dialingCode: '+1876', isActive: true },
  'HT': { country: 'Haiti', countryCode: 'HT', dialingCode: '+509', isActive: true },
  'DO': { country: 'Dominican Republic', countryCode: 'DO', dialingCode: '+1809', isActive: true },
  'PR': { country: 'Puerto Rico', countryCode: 'PR', dialingCode: '+1787', isActive: true },
  'TT': { country: 'Trinidad and Tobago', countryCode: 'TT', dialingCode: '+1868', isActive: true },
  'BB': { country: 'Barbados', countryCode: 'BB', dialingCode: '+1246', isActive: true },
  'GD': { country: 'Grenada', countryCode: 'GD', dialingCode: '+1473', isActive: true },
  'LC': { country: 'Saint Lucia', countryCode: 'LC', dialingCode: '+1758', isActive: true },
  'VC': { country: 'Saint Vincent and the Grenadines', countryCode: 'VC', dialingCode: '+1784', isActive: true },
  'AG': { country: 'Antigua and Barbuda', countryCode: 'AG', dialingCode: '+1268', isActive: true },
  'KN': { country: 'Saint Kitts and Nevis', countryCode: 'KN', dialingCode: '+1869', isActive: true },
  'DM': { country: 'Dominica', countryCode: 'DM', dialingCode: '+1767', isActive: true },
  'BS': { country: 'Bahamas', countryCode: 'BS', dialingCode: '+1242', isActive: true },

  // Europe
  'GB': { country: 'United Kingdom', countryCode: 'GB', dialingCode: '+44', isActive: true },
  'DE': { country: 'Germany', countryCode: 'DE', dialingCode: '+49', isActive: true },
  'FR': { country: 'France', countryCode: 'FR', dialingCode: '+33', isActive: true },
  'IT': { country: 'Italy', countryCode: 'IT', dialingCode: '+39', isActive: true },
  'ES': { country: 'Spain', countryCode: 'ES', dialingCode: '+34', isActive: true },
  'NL': { country: 'Netherlands', countryCode: 'NL', dialingCode: '+31', isActive: true },
  'PL': { country: 'Poland', countryCode: 'PL', dialingCode: '+48', isActive: true },
  'RU': { country: 'Russia', countryCode: 'RU', dialingCode: '+7', isActive: true },
  'CH': { country: 'Switzerland', countryCode: 'CH', dialingCode: '+41', isActive: true },
  'SE': { country: 'Sweden', countryCode: 'SE', dialingCode: '+46', isActive: true },
  'NO': { country: 'Norway', countryCode: 'NO', dialingCode: '+47', isActive: true },
  'DK': { country: 'Denmark', countryCode: 'DK', dialingCode: '+45', isActive: true },
  'FI': { country: 'Finland', countryCode: 'FI', dialingCode: '+358', isActive: true },
  'BE': { country: 'Belgium', countryCode: 'BE', dialingCode: '+32', isActive: true },
  'AT': { country: 'Austria', countryCode: 'AT', dialingCode: '+43', isActive: true },
  'IE': { country: 'Ireland', countryCode: 'IE', dialingCode: '+353', isActive: true },
  'PT': { country: 'Portugal', countryCode: 'PT', dialingCode: '+351', isActive: true },
  'GR': { country: 'Greece', countryCode: 'GR', dialingCode: '+30', isActive: true },
  'CZ': { country: 'Czech Republic', countryCode: 'CZ', dialingCode: '+420', isActive: true },
  'SK': { country: 'Slovakia', countryCode: 'SK', dialingCode: '+421', isActive: true },
  'HU': { country: 'Hungary', countryCode: 'HU', dialingCode: '+36', isActive: true },
  'RO': { country: 'Romania', countryCode: 'RO', dialingCode: '+40', isActive: true },
  'BG': { country: 'Bulgaria', countryCode: 'BG', dialingCode: '+359', isActive: true },
  'HR': { country: 'Croatia', countryCode: 'HR', dialingCode: '+385', isActive: true },
  'SI': { country: 'Slovenia', countryCode: 'SI', dialingCode: '+386', isActive: true },
  'EE': { country: 'Estonia', countryCode: 'EE', dialingCode: '+372', isActive: true },
  'LV': { country: 'Latvia', countryCode: 'LV', dialingCode: '+371', isActive: true },
  'LT': { country: 'Lithuania', countryCode: 'LT', dialingCode: '+370', isActive: true },
  'MT': { country: 'Malta', countryCode: 'MT', dialingCode: '+356', isActive: true },
  'CY': { country: 'Cyprus', countryCode: 'CY', dialingCode: '+357', isActive: true },
  'LU': { country: 'Luxembourg', countryCode: 'LU', dialingCode: '+352', isActive: true },
  'IS': { country: 'Iceland', countryCode: 'IS', dialingCode: '+354', isActive: true },
  'AL': { country: 'Albania', countryCode: 'AL', dialingCode: '+355', isActive: true },
  'MK': { country: 'North Macedonia', countryCode: 'MK', dialingCode: '+389', isActive: true },
  'ME': { country: 'Montenegro', countryCode: 'ME', dialingCode: '+382', isActive: true },
  'RS': { country: 'Serbia', countryCode: 'RS', dialingCode: '+381', isActive: true },
  'BA': { country: 'Bosnia and Herzegovina', countryCode: 'BA', dialingCode: '+387', isActive: true },
  'XK': { country: 'Kosovo', countryCode: 'XK', dialingCode: '+383', isActive: true },
  'MD': { country: 'Moldova', countryCode: 'MD', dialingCode: '+373', isActive: true },
  'UA': { country: 'Ukraine', countryCode: 'UA', dialingCode: '+380', isActive: true },
  'BY': { country: 'Belarus', countryCode: 'BY', dialingCode: '+375', isActive: true },
  'AM': { country: 'Armenia', countryCode: 'AM', dialingCode: '+374', isActive: true },
  'GE': { country: 'Georgia', countryCode: 'GE', dialingCode: '+995', isActive: true },
  'AZ': { country: 'Azerbaijan', countryCode: 'AZ', dialingCode: '+994', isActive: true },
  'KZ': { country: 'Kazakhstan', countryCode: 'KZ', dialingCode: '+7', isActive: true },
  'UZ': { country: 'Uzbekistan', countryCode: 'UZ', dialingCode: '+998', isActive: true },
  'TM': { country: 'Turkmenistan', countryCode: 'TM', dialingCode: '+993', isActive: true },
  'KG': { country: 'Kyrgyzstan', countryCode: 'KG', dialingCode: '+996', isActive: true },
  'TJ': { country: 'Tajikistan', countryCode: 'TJ', dialingCode: '+992', isActive: true },

  // Asia
  'CN': { country: 'China', countryCode: 'CN', dialingCode: '+86', isActive: true },
  'IN': { country: 'India', countryCode: 'IN', dialingCode: '+91', isActive: true },
  'JP': { country: 'Japan', countryCode: 'JP', dialingCode: '+81', isActive: true },
  'KR': { country: 'South Korea', countryCode: 'KR', dialingCode: '+82', isActive: true },
  'SG': { country: 'Singapore', countryCode: 'SG', dialingCode: '+65', isActive: true },
  'MY': { country: 'Malaysia', countryCode: 'MY', dialingCode: '+60', isActive: true },
  'TH': { country: 'Thailand', countryCode: 'TH', dialingCode: '+66', isActive: true },
  'VN': { country: 'Vietnam', countryCode: 'VN', dialingCode: '+84', isActive: true },
  'ID': { country: 'Indonesia', countryCode: 'ID', dialingCode: '+62', isActive: true },
  'PH': { country: 'Philippines', countryCode: 'PH', dialingCode: '+63', isActive: true },
  'PK': { country: 'Pakistan', countryCode: 'PK', dialingCode: '+92', isActive: true },
  'BD': { country: 'Bangladesh', countryCode: 'BD', dialingCode: '+880', isActive: true },
  'LK': { country: 'Sri Lanka', countryCode: 'LK', dialingCode: '+94', isActive: true },
  'NP': { country: 'Nepal', countryCode: 'NP', dialingCode: '+977', isActive: true },
  'BT': { country: 'Bhutan', countryCode: 'BT', dialingCode: '+975', isActive: true },
  'MV': { country: 'Maldives', countryCode: 'MV', dialingCode: '+960', isActive: true },
  'MM': { country: 'Myanmar', countryCode: 'MM', dialingCode: '+95', isActive: true },
  'LA': { country: 'Laos', countryCode: 'LA', dialingCode: '+856', isActive: true },
  'KH': { country: 'Cambodia', countryCode: 'KH', dialingCode: '+855', isActive: true },
  'MN': { country: 'Mongolia', countryCode: 'MN', dialingCode: '+976', isActive: true },
  'TW': { country: 'Taiwan', countryCode: 'TW', dialingCode: '+886', isActive: true },
  'HK': { country: 'Hong Kong', countryCode: 'HK', dialingCode: '+852', isActive: true },
  'MO': { country: 'Macau', countryCode: 'MO', dialingCode: '+853', isActive: true },
  'BN': { country: 'Brunei', countryCode: 'BN', dialingCode: '+673', isActive: true },
  'TL': { country: 'Timor-Leste', countryCode: 'TL', dialingCode: '+670', isActive: true },
  'PG': { country: 'Papua New Guinea', countryCode: 'PG', dialingCode: '+675', isActive: true },
  'FJ': { country: 'Fiji', countryCode: 'FJ', dialingCode: '+679', isActive: true },
  'NC': { country: 'New Caledonia', countryCode: 'NC', dialingCode: '+687', isActive: true },
  'VU': { country: 'Vanuatu', countryCode: 'VU', dialingCode: '+678', isActive: true },
  'SB': { country: 'Solomon Islands', countryCode: 'SB', dialingCode: '+677', isActive: true },
  'TO': { country: 'Tonga', countryCode: 'TO', dialingCode: '+676', isActive: true },
  'WS': { country: 'Samoa', countryCode: 'WS', dialingCode: '+685', isActive: true },
  'KI': { country: 'Kiribati', countryCode: 'KI', dialingCode: '+686', isActive: true },
  'TV': { country: 'Tuvalu', countryCode: 'TV', dialingCode: '+688', isActive: true },
  'NR': { country: 'Nauru', countryCode: 'NR', dialingCode: '+674', isActive: true },
  'PW': { country: 'Palau', countryCode: 'PW', dialingCode: '+680', isActive: true },
  'MH': { country: 'Marshall Islands', countryCode: 'MH', dialingCode: '+692', isActive: true },
  'FM': { country: 'Micronesia', countryCode: 'FM', dialingCode: '+691', isActive: true },
  'CK': { country: 'Cook Islands', countryCode: 'CK', dialingCode: '+682', isActive: true },
  'NU': { country: 'Niue', countryCode: 'NU', dialingCode: '+683', isActive: true },
  'TK': { country: 'Tokelau', countryCode: 'TK', dialingCode: '+690', isActive: true },
  'AS': { country: 'American Samoa', countryCode: 'AS', dialingCode: '+1684', isActive: true },
  'GU': { country: 'Guam', countryCode: 'GU', dialingCode: '+1671', isActive: true },
  'MP': { country: 'Northern Mariana Islands', countryCode: 'MP', dialingCode: '+1670', isActive: true },
  'PF': { country: 'French Polynesia', countryCode: 'PF', dialingCode: '+689', isActive: true },
  'WF': { country: 'Wallis and Futuna', countryCode: 'WF', dialingCode: '+681', isActive: true },

  // Middle East
  'SA': { country: 'Saudi Arabia', countryCode: 'SA', dialingCode: '+966', isActive: true },
  'AE': { country: 'United Arab Emirates', countryCode: 'AE', dialingCode: '+971', isActive: true },
  'TR': { country: 'Turkey', countryCode: 'TR', dialingCode: '+90', isActive: true },
  'IL': { country: 'Israel', countryCode: 'IL', dialingCode: '+972', isActive: true },
  'JO': { country: 'Jordan', countryCode: 'JO', dialingCode: '+962', isActive: true },
  'LB': { country: 'Lebanon', countryCode: 'LB', dialingCode: '+961', isActive: true },
  'SY': { country: 'Syria', countryCode: 'SY', dialingCode: '+963', isActive: true },
  'IQ': { country: 'Iraq', countryCode: 'IQ', dialingCode: '+964', isActive: true },
  'IR': { country: 'Iran', countryCode: 'IR', dialingCode: '+98', isActive: true },
  'KW': { country: 'Kuwait', countryCode: 'KW', dialingCode: '+965', isActive: true },
  'QA': { country: 'Qatar', countryCode: 'QA', dialingCode: '+974', isActive: true },
  'BH': { country: 'Bahrain', countryCode: 'BH', dialingCode: '+973', isActive: true },
  'OM': { country: 'Oman', countryCode: 'OM', dialingCode: '+968', isActive: true },
  'YE': { country: 'Yemen', countryCode: 'YE', dialingCode: '+967', isActive: true },
  'PS': { country: 'Palestine', countryCode: 'PS', dialingCode: '+970', isActive: true },

  // Africa
  'NG': { country: 'Nigeria', countryCode: 'NG', dialingCode: '+234', isActive: true },
  'ZA': { country: 'South Africa', countryCode: 'ZA', dialingCode: '+27', isActive: true },
  'EG': { country: 'Egypt', countryCode: 'EG', dialingCode: '+20', isActive: true },
  'KE': { country: 'Kenya', countryCode: 'KE', dialingCode: '+254', isActive: true },
  'GH': { country: 'Ghana', countryCode: 'GH', dialingCode: '+233', isActive: true },
  'ET': { country: 'Ethiopia', countryCode: 'ET', dialingCode: '+251', isActive: true },
  'TZ': { country: 'Tanzania', countryCode: 'TZ', dialingCode: '+255', isActive: true },
  'UG': { country: 'Uganda', countryCode: 'UG', dialingCode: '+256', isActive: true },
  'MG': { country: 'Madagascar', countryCode: 'MG', dialingCode: '+261', isActive: true },
  'MZ': { country: 'Mozambique', countryCode: 'MZ', dialingCode: '+258', isActive: true },
  'ZW': { country: 'Zimbabwe', countryCode: 'ZW', dialingCode: '+263', isActive: true },
  'ZM': { country: 'Zambia', countryCode: 'ZM', dialingCode: '+260', isActive: true },
  'MW': { country: 'Malawi', countryCode: 'MW', dialingCode: '+265', isActive: true },
  'BW': { country: 'Botswana', countryCode: 'BW', dialingCode: '+267', isActive: true },
  'NA': { country: 'Namibia', countryCode: 'NA', dialingCode: '+264', isActive: true },
  'SZ': { country: 'Eswatini', countryCode: 'SZ', dialingCode: '+268', isActive: true },
  'LS': { country: 'Lesotho', countryCode: 'LS', dialingCode: '+266', isActive: true },
  'AO': { country: 'Angola', countryCode: 'AO', dialingCode: '+244', isActive: true },
  'CD': { country: 'Democratic Republic of the Congo', countryCode: 'CD', dialingCode: '+243', isActive: true },
  'CG': { country: 'Republic of the Congo', countryCode: 'CG', dialingCode: '+242', isActive: true },
  'GA': { country: 'Gabon', countryCode: 'GA', dialingCode: '+241', isActive: true },
  'CM': { country: 'Cameroon', countryCode: 'CM', dialingCode: '+237', isActive: true },
  'CF': { country: 'Central African Republic', countryCode: 'CF', dialingCode: '+236', isActive: true },
  'TD': { country: 'Chad', countryCode: 'TD', dialingCode: '+235', isActive: true },
  'NE': { country: 'Niger', countryCode: 'NE', dialingCode: '+227', isActive: true },
  'ML': { country: 'Mali', countryCode: 'ML', dialingCode: '+223', isActive: true },
  'BF': { country: 'Burkina Faso', countryCode: 'BF', dialingCode: '+226', isActive: true },
  'CI': { country: 'Ivory Coast', countryCode: 'CI', dialingCode: '+225', isActive: true },
  'SN': { country: 'Senegal', countryCode: 'SN', dialingCode: '+221', isActive: true },
  'GN': { country: 'Guinea', countryCode: 'GN', dialingCode: '+224', isActive: true },
  'GW': { country: 'Guinea-Bissau', countryCode: 'GW', dialingCode: '+245', isActive: true },
  'SL': { country: 'Sierra Leone', countryCode: 'SL', dialingCode: '+232', isActive: true },
  'LR': { country: 'Liberia', countryCode: 'LR', dialingCode: '+231', isActive: true },
  'TG': { country: 'Togo', countryCode: 'TG', dialingCode: '+228', isActive: true },
  'BJ': { country: 'Benin', countryCode: 'BJ', dialingCode: '+229', isActive: true },
  'CV': { country: 'Cape Verde', countryCode: 'CV', dialingCode: '+238', isActive: true },
  'GM': { country: 'Gambia', countryCode: 'GM', dialingCode: '+220', isActive: true },
  'MR': { country: 'Mauritania', countryCode: 'MR', dialingCode: '+222', isActive: true },
  'DZ': { country: 'Algeria', countryCode: 'DZ', dialingCode: '+213', isActive: true },
  'TN': { country: 'Tunisia', countryCode: 'TN', dialingCode: '+216', isActive: true },
  'LY': { country: 'Libya', countryCode: 'LY', dialingCode: '+218', isActive: true },
  'SD': { country: 'Sudan', countryCode: 'SD', dialingCode: '+249', isActive: true },
  'SS': { country: 'South Sudan', countryCode: 'SS', dialingCode: '+211', isActive: true },
  'ER': { country: 'Eritrea', countryCode: 'ER', dialingCode: '+291', isActive: true },
  'DJ': { country: 'Djibouti', countryCode: 'DJ', dialingCode: '+253', isActive: true },
  'SO': { country: 'Somalia', countryCode: 'SO', dialingCode: '+252', isActive: true },
  'RW': { country: 'Rwanda', countryCode: 'RW', dialingCode: '+250', isActive: true },
  'BI': { country: 'Burundi', countryCode: 'BI', dialingCode: '+257', isActive: true },
  'KM': { country: 'Comoros', countryCode: 'KM', dialingCode: '+269', isActive: true },
  'SC': { country: 'Seychelles', countryCode: 'SC', dialingCode: '+248', isActive: true },
  'MU': { country: 'Mauritius', countryCode: 'MU', dialingCode: '+230', isActive: true },
  'RE': { country: 'Réunion', countryCode: 'RE', dialingCode: '+262', isActive: true },
  'YT': { country: 'Mayotte', countryCode: 'YT', dialingCode: '+262', isActive: true },
  'ST': { country: 'São Tomé and Príncipe', countryCode: 'ST', dialingCode: '+239', isActive: true },
  'GQ': { country: 'Equatorial Guinea', countryCode: 'GQ', dialingCode: '+240', isActive: true },
  'SH': { country: 'Saint Helena', countryCode: 'SH', dialingCode: '+290', isActive: true },
  'AC': { country: 'Ascension Island', countryCode: 'AC', dialingCode: '+247', isActive: true },
  'TA': { country: 'Tristan da Cunha', countryCode: 'TA', dialingCode: '+290', isActive: true },

  // South America
  'BR': { country: 'Brazil', countryCode: 'BR', dialingCode: '+55', isActive: true },
  'AR': { country: 'Argentina', countryCode: 'AR', dialingCode: '+54', isActive: true },
  'CO': { country: 'Colombia', countryCode: 'CO', dialingCode: '+57', isActive: true },
  'PE': { country: 'Peru', countryCode: 'PE', dialingCode: '+51', isActive: true },
  'CL': { country: 'Chile', countryCode: 'CL', dialingCode: '+56', isActive: true },
  'VE': { country: 'Venezuela', countryCode: 'VE', dialingCode: '+58', isActive: true },
  'EC': { country: 'Ecuador', countryCode: 'EC', dialingCode: '+593', isActive: true },
  'BO': { country: 'Bolivia', countryCode: 'BO', dialingCode: '+591', isActive: true },
  'PY': { country: 'Paraguay', countryCode: 'PY', dialingCode: '+595', isActive: true },
  'UY': { country: 'Uruguay', countryCode: 'UY', dialingCode: '+598', isActive: true },
  'GY': { country: 'Guyana', countryCode: 'GY', dialingCode: '+592', isActive: true },
  'SR': { country: 'Suriname', countryCode: 'SR', dialingCode: '+597', isActive: true },
  'FK': { country: 'Falkland Islands', countryCode: 'FK', dialingCode: '+500', isActive: true },
  'GF': { country: 'French Guiana', countryCode: 'GF', dialingCode: '+594', isActive: true },

  // Australia & Oceania
  'AU': { country: 'Australia', countryCode: 'AU', dialingCode: '+61', isActive: true },
  'NZ': { country: 'New Zealand', countryCode: 'NZ', dialingCode: '+64', isActive: true }
};

module.exports = { countryCodes };
