// Master theme configuration for the Voice Translator application
// This file contains user-friendly theme options with clear descriptions

const themes = {
  'light': {
    id: 'light',
    name: 'Light Theme',
    displayName: 'Light',
    description: 'Clean and bright interface with light colors',
    icon: '☀️',
    category: 'Light',
    colors: {
      background: 'bg-white',
      backgroundAlt: 'bg-white',
      card: 'bg-white',
      cardHover: 'hover:bg-gray-50',
      text: 'text-gray-900',
      textSecondary: 'text-gray-600',
      textMuted: 'text-gray-500',
      border: 'border-gray-200',
      borderHover: 'hover:border-gray-300',
      primary: 'bg-blue-600',
      primaryHover: 'hover:bg-blue-700',
      primaryText: 'text-blue-600',
      secondary: 'bg-gray-100',
      secondaryHover: 'hover:bg-gray-200',
      secondaryText: 'text-gray-700',
      accent: 'bg-indigo-100',
      accentHover: 'hover:bg-indigo-200',
      accentText: 'text-indigo-700',
      success: 'bg-green-100',
      successText: 'text-green-700',
      error: 'bg-red-100',
      errorText: 'text-red-700',
      warning: 'bg-yellow-100',
      warningText: 'text-yellow-700',
      input: 'bg-white border-gray-300 focus:border-blue-500 focus:ring-0',
      sidebar: 'bg-white border-r border-gray-200',
      header: 'bg-white border-b border-gray-200',
      shadow: 'shadow-sm',
      shadowHover: 'hover:shadow-md',
      shadowLarge: 'shadow-lg',
      selected: 'bg-blue-50 text-blue-700 border-blue-200',
      hover: 'hover:bg-gray-50'
    },
    isActive: true
  },

  'dark': {
    id: 'dark',
    name: 'Dark Theme',
    displayName: 'Dark',
    description: 'Easy on the eyes with dark colors for low-light environments',
    icon: '🌙',
    category: 'Dark',
    colors: {
      background: 'bg-gray-900',
      backgroundAlt: 'bg-gray-800',
      card: 'bg-gray-800',
      cardHover: 'hover:bg-gray-700',
      text: 'text-white',
      textSecondary: 'text-gray-300',
      textMuted: 'text-gray-400',
      border: 'border-gray-700',
      borderHover: 'hover:border-gray-600',
      primary: 'bg-blue-500',
      primaryHover: 'hover:bg-blue-600',
      primaryText: 'text-blue-400',
      secondary: 'bg-gray-700',
      secondaryHover: 'hover:bg-gray-600',
      secondaryText: 'text-gray-300',
      accent: 'bg-indigo-900',
      accentHover: 'hover:bg-indigo-800',
      accentText: 'text-indigo-300',
      success: 'bg-green-900',
      successText: 'text-green-300',
      error: 'bg-red-900',
      errorText: 'text-red-300',
      warning: 'bg-yellow-900',
      warningText: 'text-yellow-300',
      input: 'bg-gray-800 border-gray-600 focus:border-blue-500 focus:ring-0 text-white',
      sidebar: 'bg-gray-900 border-r border-gray-700',
      header: 'bg-gray-900 border-b border-gray-700',
      shadow: 'shadow-lg',
      shadowHover: 'hover:shadow-xl',
      shadowLarge: 'shadow-2xl',
      selected: 'bg-blue-900 text-blue-300 border-blue-700',
      hover: 'hover:bg-gray-700'
    },
    isActive: true
  },

  'ocean': {
    id: 'ocean',
    name: 'Ocean Theme',
    displayName: 'Ocean',
    description: 'Calming blue tones inspired by the ocean',
    icon: '🌊',
    category: 'Nature',
    colors: {
      background: 'bg-cyan-100',
      backgroundAlt: 'bg-cyan-100',
      card: 'bg-cyan-50',
      cardHover: 'hover:bg-cyan-200',
      text: 'text-slate-700',
      textSecondary: 'text-slate-600',
      textMuted: 'text-slate-500',
      border: 'border-cyan-200',
      borderHover: 'hover:border-cyan-300',
      primary: 'bg-cyan-600',
      primaryHover: 'hover:bg-cyan-700',
      primaryText: 'text-cyan-600',
      secondary: 'bg-blue-100',
      secondaryHover: 'hover:bg-blue-200',
      secondaryText: 'text-blue-700',
      accent: 'bg-indigo-100',
      accentHover: 'hover:bg-indigo-200',
      accentText: 'text-indigo-700',
      success: 'bg-teal-100',
      successText: 'text-teal-700',
      error: 'bg-rose-100',
      errorText: 'text-rose-700',
      warning: 'bg-amber-100',
      warningText: 'text-amber-700',
      input: 'bg-white border-cyan-300 focus:border-cyan-500 focus:ring-0',
      sidebar: 'bg-cyan-100 border-r border-cyan-300 shadow-lg',
      header: 'bg-cyan-100 border-b border-cyan-300',
      shadow: 'shadow-sm',
      shadowHover: 'hover:shadow-md',
      shadowLarge: 'shadow-lg',
      selected: 'bg-cyan-50 text-cyan-700 border-cyan-300',
      hover: 'hover:bg-cyan-200'
    },
    isActive: true
  },

  'sunset': {
    id: 'sunset',
    name: 'Sunset Theme',
    displayName: 'Sunset',
    description: 'Warm orange and red tones like a beautiful sunset',
    icon: '🌅',
    category: 'Nature',
    colors: {
      background: 'bg-orange-100',
      backgroundAlt: 'bg-orange-100',
      card: 'bg-orange-50',
      cardHover: 'hover:bg-orange-200',
      text: 'text-orange-900',
      textSecondary: 'text-orange-700',
      textMuted: 'text-orange-600',
      border: 'border-orange-200',
      borderHover: 'hover:border-orange-300',
      primary: 'bg-orange-600',
      primaryHover: 'hover:bg-orange-700',
      primaryText: 'text-orange-600',
      secondary: 'bg-red-100',
      secondaryHover: 'hover:bg-red-200',
      secondaryText: 'text-red-700',
      accent: 'bg-pink-100',
      accentHover: 'hover:bg-pink-200',
      accentText: 'text-pink-700',
      success: 'bg-emerald-100',
      successText: 'text-emerald-700',
      error: 'bg-red-100',
      errorText: 'text-red-700',
      warning: 'bg-amber-100',
      warningText: 'text-amber-700',
      input: 'bg-white border-orange-300 focus:border-orange-500 focus:ring-0',
      sidebar: 'bg-orange-100 border-r border-orange-300 shadow-lg',
      header: 'bg-orange-100 border-b border-orange-300',
      shadow: 'shadow-sm',
      shadowHover: 'hover:shadow-md',
      shadowLarge: 'shadow-lg',
      selected: 'bg-orange-50 text-orange-700 border-orange-300',
      hover: 'hover:bg-orange-200'
    },
    isActive: true
  },

  'forest': {
    id: 'forest',
    name: 'Forest Theme',
    displayName: 'Forest',
    description: 'Natural green tones inspired by a peaceful forest',
    icon: '🌲',
    category: 'Nature',
    colors: {
      background: 'bg-green-100',
      backgroundAlt: 'bg-green-100',
      card: 'bg-green-50',
      cardHover: 'hover:bg-green-200',
      text: 'text-green-900',
      textSecondary: 'text-green-700',
      textMuted: 'text-green-600',
      border: 'border-green-200',
      borderHover: 'hover:border-green-300',
      primary: 'bg-green-600',
      primaryHover: 'hover:bg-green-700',
      primaryText: 'text-green-600',
      secondary: 'bg-emerald-100',
      secondaryHover: 'hover:bg-emerald-200',
      secondaryText: 'text-emerald-700',
      accent: 'bg-teal-100',
      accentHover: 'hover:bg-teal-200',
      accentText: 'text-teal-700',
      success: 'bg-green-100',
      successText: 'text-green-700',
      error: 'bg-red-100',
      errorText: 'text-red-700',
      warning: 'bg-yellow-100',
      warningText: 'text-yellow-700',
      input: 'bg-white border-green-300 focus:border-green-500 focus:ring-0',
      sidebar: 'bg-green-100 border-r border-green-300 shadow-lg',
      header: 'bg-green-100 border-b border-green-300',
      shadow: 'shadow-sm',
      shadowHover: 'hover:shadow-md',
      shadowLarge: 'shadow-lg',
      selected: 'bg-green-50 text-green-700 border-green-300',
      hover: 'hover:bg-green-200'
    },
    isActive: true
  },

  'lavender': {
    id: 'lavender',
    name: 'Lavender Theme',
    displayName: 'Lavender',
    description: 'Soft purple tones for a calming and elegant experience',
    icon: '💜',
    category: 'Elegant',
    colors: {
      background: 'bg-purple-100',
      backgroundAlt: 'bg-purple-100',
      card: 'bg-purple-50',
      cardHover: 'hover:bg-purple-200',
      text: 'text-purple-900',
      textSecondary: 'text-purple-700',
      textMuted: 'text-purple-600',
      border: 'border-purple-200',
      borderHover: 'hover:border-purple-300',
      primary: 'bg-purple-600',
      primaryHover: 'hover:bg-purple-700',
      primaryText: 'text-purple-600',
      secondary: 'bg-violet-100',
      secondaryHover: 'hover:bg-violet-200',
      secondaryText: 'text-violet-700',
      accent: 'bg-indigo-100',
      accentHover: 'hover:bg-indigo-200',
      accentText: 'text-indigo-700',
      success: 'bg-emerald-100',
      successText: 'text-emerald-700',
      error: 'bg-red-100',
      errorText: 'text-red-700',
      warning: 'bg-amber-100',
      warningText: 'text-amber-700',
      input: 'bg-white border-purple-300 focus:border-purple-500 focus:ring-0',
      sidebar: 'bg-purple-100 border-r border-purple-300 shadow-lg',
      header: 'bg-purple-100 border-b border-purple-300',
      shadow: 'shadow-sm',
      shadowHover: 'hover:shadow-md',
      shadowLarge: 'shadow-lg',
      selected: 'bg-purple-50 text-purple-700 border-purple-300',
      hover: 'hover:bg-purple-200'
    },
    isActive: true
  },

  'rose': {
    id: 'rose',
    name: 'Rose Theme',
    displayName: 'Rose',
    description: 'Romantic pink and rose tones for a gentle experience',
    icon: '🌹',
    category: 'Elegant',
    colors: {
      background: 'bg-pink-100',
      backgroundAlt: 'bg-pink-100',
      card: 'bg-pink-50',
      cardHover: 'hover:bg-pink-200',
      text: 'text-pink-900',
      textSecondary: 'text-pink-700',
      textMuted: 'text-pink-600',
      border: 'border-pink-200',
      borderHover: 'hover:border-pink-300',
      primary: 'bg-pink-600',
      primaryHover: 'hover:bg-pink-700',
      primaryText: 'text-pink-600',
      secondary: 'bg-rose-100',
      secondaryHover: 'hover:bg-rose-200',
      secondaryText: 'text-rose-700',
      accent: 'bg-red-100',
      accentHover: 'hover:bg-red-200',
      accentText: 'text-red-700',
      success: 'bg-emerald-100',
      successText: 'text-emerald-700',
      error: 'bg-red-100',
      errorText: 'text-red-700',
      warning: 'bg-amber-100',
      warningText: 'text-amber-700',
      input: 'bg-white border-pink-300 focus:border-pink-500 focus:ring-0',
      sidebar: 'bg-pink-100 border-r border-pink-300 shadow-lg',
      header: 'bg-pink-100 border-b border-pink-300',
      shadow: 'shadow-sm',
      shadowHover: 'hover:shadow-md',
      shadowLarge: 'shadow-lg',
      selected: 'bg-pink-50 text-pink-700 border-pink-300',
      hover: 'hover:bg-pink-200'
    },
    isActive: true
  }
};

module.exports = { themes };
